stages:
  - testManual

e2e-tests:
  stage: testManual
  image: mcr.microsoft.com/playwright:v1.42.1-jammy
  # tags:
  #   - shell # ou runner tag que você estiver usando
  script:
    - yarn install
    - yarn playwright install
    - yarn run e2e
  only:
  when: manual
