# CI de Nível 01 - Disparo Manual a partir de um clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos) ou tiggers
# gatilho de execução manual  =  workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas que serão executadas dentro do pipeline = jobs

jobs:
  e2e-tests:
    #maquina que o job irá executar
    runs-on: ubuntu-latest

    #passos do scritp de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalaçao do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #instalaçao dependencias do yarn
      - name: Instalando dependências
        run: yarn

      #Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      #Executar o teste e2e
      - name: Executando Testes
        run: yarn run e2e
