# CI de Nível 03 - Disparo após aconclusão de um pipeline

# nome do nosso 'pipeline' 
name: 'Execução por Deploy'

# regras de disparo (gatilhos) ou tiggers 
# gatilho de execução manual  =  workflow_dispatch
# gatilho de execução agendade  =  scheldule
# gatilho de execução a partir de outro pipe  =  workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']  #nome da pipeline que irá monitorar
    types: # somente para quando a pipeline estiver com o status completed 
      - completed

# trabalhos/tarefas que serão executadas dentro do pipeline = jobs

jobs:
  e2e-tests:

    #maquina que o job irá executar
    runs-on: ubuntu-latest

    # condicional - if
    # '${ expressao }'
    # == comparacao
    
    if: ${{ github.event.workflow_run.conclusion ==  'success' }}

    #passos do scritp de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalaçao do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #instalaçao dependencias do yarn
      - name: Instalando dependências
        run: yarn 

      #Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install
      
      #Executar o teste e2e
      - name: Executando Testes
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}  # ira gerar o relatório para todas as pipes que nao fora canceladas
        with:
          name: relatorio
          path: ./playwright-report